### ISSUE TITLE
Problem with sbt 1.4._

### ISSUE THREAD

**Issue by apoigne** [julianpeeters/avrohugger#145]
If using sbt 1.4.4 for my project, I get an error message

 java.lang.NoSuchMethodError: scala.jdk.CollectionConverters$.RichConcurrentHashMap(Ljava/util/concurrent/ConcurrentHashMap;)Lscala/jdk/CollectionConverters$RichConcurrentHashMap;

The project works well with sbt 1.3.13

**Comment by TidyMaze** [comment]
The PR #143 includes a fix for this, not reviewed yet

**Comment by julianpeeters** [comment]
thank you for the reports, @apoigne and @TidyMaze , this should be fixed now in avrohugger 1.0.0-RC23 and sbt-avrohugger 2.0.0-RC23
